# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ErrorBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_ErrorBoxWidget(object):
    def setupUi(self, Widget,message):

        "widget"
        Widget.setWindowTitle("Error")
        Widget.setObjectName("ErrorWidget")
        Widget.setStyleSheet("background-color:rgba(22,5,12,255)")
        Widget.setWindowIcon(QtGui.QIcon("images/icons8-cráneo-lindo-100.png"))
        Widget.setMaximumSize(400, 400)
        self.verticalLayuot0=QtWidgets.QVBoxLayout(Widget)
        self.verticalLayuot0.setContentsMargins(0, 0, 0, 10)
        self.verticalLayuot0.setSpacing(0)
        self.verticalLayuot0.setObjectName("VerticalLayout")

        "frame1"

        self.frame1 = QtWidgets.QFrame(Widget)
        self.frame1.setStyleSheet("background-color:none")
        self.verticalLayout1=QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout1.setContentsMargins(0,0,0,0)
        self.verticalLayout1.setSpacing(0)
        self.verticalLayout1.setObjectName("verticalLayout2")

        "GifPlaye"
        self.label1 = QtWidgets.QLabel(self.frame1)
        self.gif = QMovie('images/RedCal.gif')
        self.label1.setMovie(self.gif)
        self.label1.setAlignment(Qt.AlignCenter)
        self.gif.start()

        "message"
        self.label2 = QtWidgets.QLabel(self.frame1)
        self.label2.setText(message)
        self.label2.setFont(QFont("Times New Roman", 18))
        self.label2.setStyleSheet("color:white")
        self.label2.setAlignment(Qt.AlignCenter)
        self.label2.raise_()
        self.label2.show()

        "frame 2"

        self.frame2 = QtWidgets.QFrame(Widget)
        self.frame2.setStyleSheet("background-color:none;"
                                  "border-style:solid;"
                                  "border-width:0;"
                                  "border-color:none")
        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout2.setSpacing(0)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.OkButton2 = QtWidgets.QPushButton(self.frame2, clicked=lambda:Widget.close())
        self.OkButton2.setText("Ok")
        self.OkButton2.setStyleSheet(
            "QPushButton {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, "
            "stop:0.2 rgba(0, 0, 0, 180), stop:1 rgba(0, 0, 0, 0));\n "
            "color:rgba(255,255,255,150);\n"
            "border-style:solid;}\n"
            "QPushButton:pressed {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, "
            "fy:0.5, stop:0.2 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n "
            "color:rgba(255,255,255,255);\n"
            "border-style:solid;}")
        self.OkButton2.resize(self.OkButton2.sizeHint())
        self.frame2.setMaximumSize(12000,80)
        "verticallayout"
        self.verticalLayout1.addWidget(self.label2)
        self.verticalLayout1.addWidget(self.label1)
        self.verticalLayout2.addWidget(self.OkButton2)
        self.verticalLayuot0.addWidget(self.frame1)
        self.verticalLayuot0.addWidget(self.frame2)


    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_ErrorBoxWidget()
    ui.setupUi(Widget,"hola")
    Widget.show()
    sys.exit(app.exec_())
