# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from re import match
from MCUA import Ui_MCUA
from FreeFall import Ui_FreeFall
from MRUA import Ui_MRUA
from PyQt5 import QtCore, QtGui, QtWidgets
from ErrorBox import Ui_ErrorBoxWidget

class Ui_MainSimulatorWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super(Ui_MainSimulatorWindow, self).__init__()
        self.messageui = None
        self.messagewidget = None
        self.cwidgetui = None
        self.cwidget = None
        self.currentButton: str()
        self.currentButton = None
        "variables start"

        "main start"
        self.setObjectName("MainSimulatorWindow")
        self.resize(752, 724)
        self.setWindowIcon(QtGui.QIcon("images/icons8-newton-64.png"))
        self.Simulador = QtWidgets.QWidget(self)
        self.Simulador.setObjectName("Simulador")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Simulador)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        "frame1"
        self.frame = QtWidgets.QFrame(self.Simulador)
        self.frame.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.5\n"
                                 "rgba(0, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
                                 "border-style:none")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        "frame2"

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setStyleSheet("background-color:none")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        "exit button"

        self.EXITbuttom = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.EXITbuttom.setFont(font)
        self.EXITbuttom.setStyleSheet(
            ""
            "text-align: center;"
            "QPushButton{background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, "
            "stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));color:rgba(255,255,255,"
            "180);border-style:solid}\n "
            "QPushButton:pressed{background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, "
            "fy:0.5, stop:0.2 rgba(255, 0, 0, 255), stop:1 rgba(0, 0, 0, 255));color:rgba(255,255,255,"
            "255);border-style:solid}")
        self.EXITbuttom.setObjectName("EXITbuttom")
        self.EXITbuttom.clicked.connect(self.exitbut)

        self.horizontalLayout.addWidget(self.EXITbuttom)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color:none")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("border-style:none\n"
                                   "")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        "Colition radio button"

        """self.COLITIONbuttom = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.COLITIONbuttom.setFont(font)
        self.COLITIONbuttom.setStyleSheet(
            "QRadioButton{background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, "
            "stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));color:rgba(255,255,255,"
            "180);border-style:solid}\n "
            "QRadioButton:pressed{background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, "
            "fy:0.5, stop:0.2 rgba(255, 0, 0, 255), stop:1 rgba(0, 0, 0, 255));color:rgba(255,255,255,"
            "255);border-style:solid}")
        self.COLITIONbuttom.setObjectName("COLITIONbuttom")
        self.horizontalLayout_2.addWidget(self.COLITIONbuttom)"""

        "MCUA button"

        self.MCUAbuttom = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.MCUAbuttom.setFont(font)
        self.MCUAbuttom.setStyleSheet(
            """QRadioButton{
                background-color: rgba(255,0,0,130);
                color: rgba(255,255,255,180);
                border-radius:10
                }

                QRadioButton::indicator {
                width: 11px;
                height: 11px;
                border-radius: 5px;
                color:none;
                }

                QRadioButton:checked{
                background-color:rgba(255,0,0,255);
                color:white;
                }""")
        self.MCUAbuttom.setObjectName("MCUAbuttom")
        self.horizontalLayout_2.addWidget(self.MCUAbuttom)

        "MRUA button"

        self.MRUAbuttom = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.MRUAbuttom.setFont(font)
        self.MRUAbuttom.setStyleSheet(
            """QRadioButton{
                background-color: rgba(255,0,0,130);
                color: rgba(255,255,255,180);
                border-radius:10
                }

                QRadioButton::indicator {
                width: 11px;
                height: 11px;
                border-radius: 5px;
                color:none;
                }

                QRadioButton:checked{
                background-color:rgba(255,0,0,255);
                color:white;
                }""")
        self.MRUAbuttom.setObjectName("MRUAbuttom")
        self.horizontalLayout_2.addWidget(self.MRUAbuttom)

        "FreeFall button"

        self.FreeFallbuttom = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.FreeFallbuttom.setFont(font)
        self.FreeFallbuttom.setStyleSheet(
            """QRadioButton{
                background-color: rgba(255,0,0,130);
                color: rgba(255,255,255,180);
                border-radius:10;
                }


                QRadioButton::indicator {
                width: 11px;
                height: 11px;
                border-radius: 5px;
                color:none;
                }

                QRadioButton:checked{
                background-color:rgba(255,0,0,255);
                color:white;
                }""")
        self.FreeFallbuttom.setObjectName("FreeFallbuttom")
        self.horizontalLayout_2.addWidget(self.FreeFallbuttom)

        "buttons actions"
        """self.COLITIONbuttom.toggled.connect(lambda: self.collitionbutton(self.COLITIONbuttom.objectName()))"""
        self.MCUAbuttom.toggled.connect(lambda: self.mcuabutton(self.MCUAbuttom.objectName()))
        self.MRUAbuttom.toggled.connect(lambda: self.mruabutton(self.MRUAbuttom.objectName()))
        self.FreeFallbuttom.toggled.connect(lambda: self.freefallbutton(self.FreeFallbuttom.objectName()))

        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("border-style:none")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4.addWidget(self.frame_6)

        "Load Button"

        self.LoadButton = QtWidgets.QPushButton(self.frame_5, clicked=lambda: self.loadButton())
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.LoadButton.setFont(font)
        self.LoadButton.setStyleSheet(
            "QPushButton{background-color:rgba(255,255,255,160);color:rgba(0,0,0,180);"
            "border-style:solid;border-radius:5}\n "
            "QPushButton:pressed{background-color:rgba(255,255,255,255);color:rgba(0,0,0,"
            "255);border-style:solid;border-radius:5}")
        self.LoadButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.LoadButton)

        self.verticalLayout_5.addWidget(self.frame_5)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.setCentralWidget(self.Simulador)
        self.statusBar = QtWidgets.QStatusBar(self)
        self.statusBar.setObjectName("statusBar")
        self.setStatusBar(self.statusBar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def exitbut(self):
        sys.exit()

    def freefallbutton(self, but):
        self.currentButton = but

    def collitionbutton(self, but):
        self.currentButton = but

    def mcuabutton(self, but):
        self.currentButton = but

    def mruabutton(self, but):
        self.currentButton = but

    def loadButton(self):
        if self.currentButton=="FreeFallbuttom":

            self.cwidget = Ui_FreeFall(self)
            self.cwidget.show()
            MainSimulatorWindow.hide()

        elif self.currentButton == "MRUAbuttom":
            self.cwidget = QtWidgets.QWidget()
            self.cwidgetui = Ui_MRUA()
            self.cwidgetui.setupUi(self.cwidget, MainSimulatorWindow)
            self.cwidget.show()
            MainSimulatorWindow.hide()
            pass
        elif self.currentButton == "MCUAbuttom":
            self.cwidget = QtWidgets.QWidget()
            self.cwidgetui = Ui_MCUA()
            self.cwidgetui.setupUi(self.cwidget, MainSimulatorWindow)
            self.cwidget.show()
            MainSimulatorWindow.hide()
            pass
        elif self.currentButton == "":
            pass
        elif self.currentButton is None:

            self.messagewidget = QtWidgets.QWidget()
            self.messageui = Ui_ErrorBoxWidget()
            self.messageui.setupUi(self.messagewidget, "SELECCIONA \nMODO")
            self.messagewidget.show()


    def retranslateUi(self, MainSimulatorWindow):
        _translate = QtCore.QCoreApplication.translate
        MainSimulatorWindow.setWindowTitle(_translate("MainSimulatorWindow", "PYSIMULATOR"))
        self.label.setText(_translate("MainSimulatorWindow",
                                      "<html><head/><body><p>PYSIMULATOR<span style=\" "
                                      "font-size:9pt;\">byJesusAragon</span></p></body></html>"))
        self.EXITbuttom.setText(_translate("MainSimulatorWindow", "Exit"))
        """self.COLITIONbuttom.setText(_translate("MainSimulatorWindow", "COLITIONS"))"""
        self.MCUAbuttom.setText(_translate("MainSimulatorWindow", "MCUA"))
        self.MRUAbuttom.setText(_translate("MainSimulatorWindow", "MRUA"))
        self.FreeFallbuttom.setText(_translate("MainSimulatorWindow", "FreeFall"))
        self.LoadButton.setText(_translate("MainSimulatorWindow", "LOAD"))




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainSimulatorWindow = Ui_MainSimulatorWindow()
    MainSimulatorWindow.show()
    sys.exit(app.exec_())