# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MCUA.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MCUA(object):
    def setupUi(self, MCUA, Main_W):
        MCUA.setObjectName("MCUA")
        MCUA.resize(863, 800)
        MCUA.setMinimumSize(QtCore.QSize(0, 800))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MCUA)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(MCUA)
        self.frame.setStyleSheet("background-color:black;\n"
                                 "border-style:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setStyleSheet("background-color:none")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.Exitbuttom = QtWidgets.QPushButton(self.frame_2, clicked=lambda: self.exitbuttom(MCUA, Main_W))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Exitbuttom.setFont(font)
        self.Exitbuttom.setStyleSheet(
            "QPushButton {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 0));\n"
            "color:rgba(255,255,255,150);\n"
            "border-style:solid;}\n"
            "QPushButton:pressed {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
            "color:rgba(255,255,255,255);\n"
            "border-style:solid;}")
        self.Exitbuttom.setObjectName("Exitbuttom")
        self.horizontalLayout_2.addWidget(self.Exitbuttom)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,255,255,200);\n"
                                   "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.5 rgba(255, 0, 0, 180),stop:1 rgba(0,0,0,0))\n"
                                   "")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.acceleration_input = QtWidgets.QTextEdit(self.frame_4)
        self.acceleration_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.acceleration_input.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                              "color:white")
        self.acceleration_input.setObjectName("acceleration_input")
        self.verticalLayout_2.addWidget(self.acceleration_input)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,200)")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.startingspeed_input = QtWidgets.QTextEdit(self.frame_4)
        self.startingspeed_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.startingspeed_input.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                               "color:white")
        self.startingspeed_input.setObjectName("startingspeed_input")
        self.verticalLayout_2.addWidget(self.startingspeed_input)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,200)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.mass_input = QtWidgets.QTextEdit(self.frame_4)
        self.mass_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.mass_input.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                      "color:white")
        self.mass_input.setObjectName("mass_input")
        self.verticalLayout_2.addWidget(self.mass_input)
        self.LoadSImulationBUttom = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.LoadSImulationBUttom.setFont(font)
        self.LoadSImulationBUttom.setStyleSheet(
            "QPushButton {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,150);\n"
            "border-style:solid;}\n"
            "QPushButton:pressed {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 255), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,255);\n"
            "border-style:solid;}")
        self.LoadSImulationBUttom.setObjectName("LoadSImulationBUttom")
        self.verticalLayout_2.addWidget(self.LoadSImulationBUttom)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.SimulationFrame = QtWidgets.QFrame(self.frame_3)
        self.SimulationFrame.setStyleSheet("border-style:inset;\n"
                                           "border-color:rgba(255,0,0,130);\n"
                                           "border-width:5")
        self.SimulationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SimulationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SimulationFrame.setObjectName("SimulationFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SimulationFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.graphics_view = QtWidgets.QGraphicsView(self.SimulationFrame)
        self.graphics_view.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                         "border-color:none;border-style:solid")
        self.graphics_view.setObjectName("graphics_view")
        self.horizontalLayout_4.addWidget(self.graphics_view)
        self.horizontalLayout_3.addWidget(self.SimulationFrame)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgba(255,255,255,200);\n"
                                    "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.5 rgba(255, 0, 0, 180),stop:1 rgba(0,0,0,0))\n"
                                    "")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.acceleration_input_3 = QtWidgets.QTextEdit(self.frame_5)
        self.acceleration_input_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.acceleration_input_3.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                                "color:white")
        self.acceleration_input_3.setObjectName("acceleration_input_3")
        self.verticalLayout_5.addWidget(self.acceleration_input_3)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgba(255,255,255,200);\n"
                                    "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.5 rgba(255, 0, 0, 180),stop:1 rgba(0,0,0,0))\n"
                                    "")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.acceleration_input_4 = QtWidgets.QTextEdit(self.frame_5)
        self.acceleration_input_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.acceleration_input_4.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                                "color:white")
        self.acceleration_input_4.setObjectName("acceleration_input_4")
        self.verticalLayout_5.addWidget(self.acceleration_input_4)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,200)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.height_input = QtWidgets.QTextEdit(self.frame_5)
        self.height_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.height_input.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                        "color:white\n"
                                        "")
        self.height_input.setObjectName("height_input")
        self.verticalLayout_5.addWidget(self.height_input)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 2)
        self.verticalLayout_5.setStretch(3, 1)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)

        self.retranslateUi(MCUA)
        QtCore.QMetaObject.connectSlotsByName(MCUA)

    def retranslateUi(self, MCUA):
        _translate = QtCore.QCoreApplication.translate
        MCUA.setWindowTitle(_translate("MCUA", "MCUA"))
        self.label.setText(_translate("MCUA",
                                      "<html><head/><body><p><span style=\" font-size:14pt;\">PYSIMULATOR<br/>MCUA</span></p></body></html>"))
        self.Exitbuttom.setText(_translate("MCUA", "BACK"))
        self.label_5.setText(_translate("MCUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">ACCELERATION </span></p><p align=\"center\"><span style=\" font-size:12pt;\">(rads/s</span><span style=\" font-size:12pt; vertical-align:super;\">2</span><span style=\" font-size:12pt;\">)</span></p></body></html>"))
        self.label_2.setText(_translate("MCUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">STARTING SPEED </span></p><p align=\"center\"><span style=\" font-size:10pt;\">w(m/s)<br/></span></p></body></html>"))
        self.label_3.setText(_translate("MCUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">MASS(kg)</span></p></body></html>"))
        self.LoadSImulationBUttom.setText(_translate("MCUA", "LOAD"))
        self.label_10.setText(_translate("MCUA",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">RADIO(m)</span></p></body></html>"))
        self.label_11.setText(_translate("MCUA",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">CENTRIPETAL<br/>ACCELERATION</span></p></body></html>"))
        self.label_4.setText(_translate("MCUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">STARTING POS </span></p><p align=\"center\">°(radians)</p></body></html>"))

    def exitbuttom(self, MCUA, Main_W):
        Main_W.show()
        MCUA.close()
        pass


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MCUA = QtWidgets.QWidget()
    ui = Ui_MCUA()
    ui.setupUi(MCUA)
    MCUA.show()
    sys.exit(app.exec_())
