# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MRUA.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MRUA(object):
    def setupUi(self, MRUA, main_w):
        MRUA.setObjectName("MRUA")
        MRUA.resize(816, 654)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MRUA)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(MRUA)
        self.frame.setStyleSheet("background-color:black;\n"
                                 "border-style:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setStyleSheet("background-color:none")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.Exitbuttom = QtWidgets.QPushButton(self.frame_2, clicked=lambda: self.exitbuttom(MRUA, main_w))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Exitbuttom.setFont(font)
        self.Exitbuttom.setStyleSheet(
            "QPushButton {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 0));\n"
            "color:rgba(255,255,255,150);\n"
            "border-style:solid;}\n"
            "QPushButton:pressed {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 255), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,255);\n"
            "border-style:solid;}")
        self.Exitbuttom.setObjectName("Exitbuttom")
        self.horizontalLayout_2.addWidget(self.Exitbuttom)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,255,255,200);\n"
                                   "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.5 rgba(255, 0, 0, 180),stop:1 rgba(0,0,0,0))\n"
                                   "")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                    "color:white")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setMaximumSize(160000, 40)
        self.verticalLayout_2.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,200)")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.SpeedTextEdit = QtWidgets.QTextEdit(self.frame_4)
        self.SpeedTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.SpeedTextEdit.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                         "color:white")
        self.SpeedTextEdit.setObjectName("SpeedTextEdit")
        self.verticalLayout_2.addWidget(self.SpeedTextEdit)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba("
            "255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n "
            "color:rgba(255,255,255,200)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.MassTextEdit = QtWidgets.QTextEdit(self.frame_4)
        self.MassTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MassTextEdit.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                        "color:white")
        self.MassTextEdit.setObjectName("MassTextEdit")
        self.verticalLayout_2.addWidget(self.MassTextEdit)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(
            "background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,200)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.HeightTextEdit = QtWidgets.QTextEdit(self.frame_4)
        self.HeightTextEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.HeightTextEdit.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                          "color:white\n"
                                          "")
        self.HeightTextEdit.setObjectName("HeightTextEdit")
        self.verticalLayout_2.addWidget(self.HeightTextEdit)
        self.LoadSImulationBUttom = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.LoadSImulationBUttom.setFont(font)
        self.LoadSImulationBUttom.setStyleSheet(
            "QPushButton {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 180), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,150);\n"
            "border-style:solid;}\n"
            "QPushButton:pressed {background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.2 rgba(255, 0, 0, 255), stop:1 rgba(0, 0, 0, 255));\n"
            "color:rgba(255,255,255,255);\n"
            "border-style:solid;}")
        self.LoadSImulationBUttom.setObjectName("LoadSImulationBUttom")
        self.verticalLayout_2.addWidget(self.LoadSImulationBUttom)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.SimulationFrame = QtWidgets.QFrame(self.frame_3)
        self.SimulationFrame.setStyleSheet("border-style:inset;\n"
                                           "border-color:rgba(255,0,0,130);\n"
                                           "border-width:5")
        self.SimulationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SimulationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SimulationFrame.setObjectName("SimulationFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SimulationFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.SimulationFrame)
        self.graphicsView.setStyleSheet("background-color:rgba(255,255,255,130);\n"
                                        "border-color:none;border-style:solid")
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout_3.addWidget(self.SimulationFrame)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)

        self.retranslateUi(MRUA)
        QtCore.QMetaObject.connectSlotsByName(MRUA)

    def retranslateUi(self, MRUA):
        _translate = QtCore.QCoreApplication.translate
        MRUA.setWindowTitle(_translate("MRUA", "MRUA"))
        self.label.setText(_translate("MRUA",
                                      "<html><head/><body><p><span style=\" "
                                      "font-size:14pt;\">PYSIMULATOR<br/>MRUA</span></p></body></html>"))
        self.Exitbuttom.setText(_translate("MRUA", "BACK"))
        self.label_5.setText(_translate("MRUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" "
                                        "font-size:12pt;\">ACCELERATION </span></p><p align=\"center\"><span style=\" "
                                        "font-size:12pt;\">Ao(m/s</span><span style=\" font-size:12pt; "
                                        "vertical-align:super;\">2</span><span style=\" "
                                        "font-size:12pt;\">)</span></p></body></html>"))
        self.label_2.setText(_translate("MRUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" "
                                        "font-size:10pt;\">STARTING SPEED <br/>Vo(m/s)</span></p></body></html>"))
        self.label_3.setText(_translate("MRUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" "
                                        "font-size:10pt;\">MASS(kg)</span></p></body></html>"))
        self.label_4.setText(_translate("MRUA",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">STARTING POS </span></p><p align=\"center\"><span style=\" font-size:10pt;\">Xo(m)</span></p></body></html>"))
        self.LoadSImulationBUttom.setText(_translate("MRUA", "LOAD"))

    def exitbuttom(self, mrua, main_w):
        main_w.show()
        mrua.close()

        pass


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MRUA = QtWidgets.QWidget()
    ui = Ui_MRUA()
    ui.setupUi(MRUA)
    MRUA.show()
    sys.exit(app.exec_())
