# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MCUA.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

bottom_style_1 = """QRadioButton{
                        background-color: rgba(255,0,0,130);
                        color: rgba(255,255,255,180);
                        border-radius:10
                        }

                        QRadioButton::indicator {
                        width: 11px;
                        height: 11px;
                        border-radius: 5px;
                        color:none;
                        }

                        QRadioButton:checked{
                        background-color:rgba(255,0,0,255);
                        color:white;
                        }"""

# label style

labelStyle = "background-color:rgba(255,0,0,130);color:rgba(255,255,255," \
             "180);border-style:solid;border-radius:5"

# font

labelFont = QtGui.QFont()
labelFont.setFamily("Segoe UI Black")
labelFont.setPointSize(15)
labelFont.setBold(True)
labelFont.setWeight(75)

# Push Button Style

pushButtonStyle = "QPushButton{background-color:rgba(255,0,0,130);color:rgba(255,255,255," \
                  "180);border-style:solid;border-radius:5}\n " \
                  "QPushButton:pressed{background-color:rgba(255,0,0,255);color:rgba(255,255,255," \
                  "255);border-style:solid;border-radius:5}"


class McuaFrame1(QtWidgets.QFrame):
    def __init__(self, parent_widget):
        super(McuaFrame1, self).__init__(parent_widget)
        self.layout = QtWidgets.QHBoxLayout(self)

        # frame 1

        self.frame_1 = QtWidgets.QFrame(self)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1Layout = QtWidgets.QVBoxLayout(self.frame_1)

        self.acceleration_label_5 = QtWidgets.QLabel(self.frame_1)
        self.acceleration_label_5.setFont(labelFont)
        self.acceleration_label_5.setStyleSheet(labelStyle)
        self.frame1Layout.addWidget(self.acceleration_label_5)

        self.acceleration_input = QtWidgets.QTextEdit(self.frame_1)
        self.acceleration_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.acceleration_input.setStyleSheet(labelStyle)
        self.frame1Layout.addWidget(self.acceleration_input)
        self.layout.addWidget(self.frame_1)

        # frame 2

        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2layout = QtWidgets.QVBoxLayout(self.frame_2)

        self.start_speed_label = QtWidgets.QLabel(self.frame_2)
        self.start_speed_label.setFont(labelFont)
        self.start_speed_label.setStyleSheet(labelStyle)
        self.frame2layout.addWidget(self.start_speed_label)

        self.starting_speed_input = QtWidgets.QTextEdit(self.frame_2)
        self.starting_speed_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.starting_speed_input.setStyleSheet(labelStyle)
        self.frame2layout.addWidget(self.starting_speed_input)

        self.layout.addWidget(self.frame_2)

        # frame 3

        self.frame_3 = QtWidgets.QFrame(self)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3layout = QtWidgets.QVBoxLayout(self.frame_3)

        self.mass_label = QtWidgets.QLabel(self.frame_3)
        self.mass_label.setStyleSheet(labelStyle)
        self.mass_label.setFont(labelFont)
        self.frame3layout.addWidget(self.mass_label)

        self.mass_input = QtWidgets.QTextEdit(self.frame_3)
        self.mass_input.setStyleSheet(labelStyle)
        self.mass_input.setMaximumSize(16000, 40)
        self.frame3layout.addWidget(self.mass_input)

        self.layout.addWidget(self.frame_3)

        # translate labels

        _translate = QtCore.QCoreApplication.translate

        self.acceleration_label_5.setText(_translate("MCUA",
                                                     "<html><head/><body><p align=\"center\">ACCELERATION"
                                                     "<br/>(rads/s²)</span></p></body></html>"))
        self.start_speed_label.setText(_translate("MCUA",
                                                  "<html><head/><body><p align=\"center\">STARTING SPEED "
                                                  "<br/>Vo(rads/s)</span></p></body></html>"))
        self.mass_label.setText(_translate("MCUA",
                                           "<html><head/><body><p align=\"center\">MASS("
                                           "kg)</span></p></body></html>"))

    def getText(self):
        acceleration = self.acceleration_input.toPlainText()
        starting_speed = self.starting_speed_input.toPlainText()
        mass = self.mass_input.toPlainText()
        try:
            values: list[float] = None
        except ValueError:
            return None
        pass


class McuaFrame2(QtWidgets.QFrame):
    def __init__(self, parent_widget):
        super(McuaFrame2, self).__init__(parent_widget)
        self.layout = QtWidgets.QHBoxLayout(self)

        # frame 1

        self.frame_1 = QtWidgets.QFrame(self)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_1_1 = QtWidgets.QVBoxLayout(self.frame_1)

        self.label_1 = QtWidgets.QLabel(self.frame_1)
        self.label_1.setFont(labelFont)
        self.label_1.setStyleSheet(labelStyle)
        self.verticalLayout_1_1.addWidget(self.label_1)

        self.radio_input = QtWidgets.QTextEdit(self.frame_1)
        self.radio_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.radio_input.setStyleSheet(labelStyle)
        self.verticalLayout_1_1.addWidget(self.radio_input)

        self.layout.addWidget(self.frame_1)

        # frame 2

        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_2_1 = QtWidgets.QVBoxLayout(self.frame_2)

        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setFont(labelFont)
        self.label_2.setStyleSheet(labelStyle)
        self.verticalLayout_2_1.addWidget(self.label_2)

        self.centripetal_acceleration_input = QtWidgets.QTextEdit(self.frame_2)
        self.centripetal_acceleration_input.setMaximumSize(QtCore.QSize(16777215, 40))
        self.centripetal_acceleration_input.setStyleSheet(labelStyle)
        self.verticalLayout_2_1.addWidget(self.centripetal_acceleration_input)

        self.layout.addWidget(self.frame_2)

        # frame 3

        self.frame_3 = QtWidgets.QFrame(self)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)

        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setFont(labelFont)
        self.label_3.setStyleSheet(labelStyle)
        self.verticalLayout_3.addWidget(self.label_3)

        self.starting_position_input = QtWidgets.QTextEdit(self.frame_3)
        self.starting_position_input.setStyleSheet(labelStyle)
        self.starting_position_input.setMaximumSize(16000, 40)
        self.verticalLayout_3.addWidget(self.starting_position_input)

        self.layout.addWidget(self.frame_3)

        # translate labels

        _translate = QtCore.QCoreApplication.translate

        self.label_1.setText(_translate("MCUA",
                                        "<html><head/><body><p align=\"center\">Radio(m)"
                                        "</span></p></body></html>"))
        self.label_2.setText(_translate("MCUA",
                                        "<html><head/><body><p align=\"center\">CENTRIPETAL"
                                        "<br/>ACCELERATION</span></p></body></html>"))
        self.label_3.setText(_translate("MCUA",
                                        "<html><head/><body><p align=\"center\">STARTING POS"
                                        "<br/>°(radians)</span></p></body></html>"))

    def getText(self):
        radio = self.radio_input.toPlainText()
        centripetal_acceleration = self.centripetal_acceleration_input.toPlainText()
        starting_pos = self.starting_position_input.toPlainText()
        try:
            values: list[float] = float(radio), float(centripetal_acceleration), float(starting_pos)
        except ValueError:
            return None
        return values
